[package]
name = "crowdsale-io"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
gstd.workspace = true
gmeta = { workspace = true, features = ["codegen"] }
scale-info.workspace = true
parity-scale-codec.workspace = true
hashbrown.workspace = true
ft-main-io.workspace = true
